// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLaD14YIQp_p8HKb0zmQx7HWL4WDN84e4',
    appId: '1:78450892577:web:548eadbf6191261251a860',
    messagingSenderId: '78450892577',
    projectId: 'myapp-2025-soknao',
    authDomain: 'myapp-2025-soknao.firebaseapp.com',
    storageBucket: 'myapp-2025-soknao.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkN5eysCoxINJ2db7rLrNd7fxMUdDDJeA',
    appId: '1:78450892577:android:6c80d0e79b8ac6e251a860',
    messagingSenderId: '78450892577',
    projectId: 'myapp-2025-soknao',
    storageBucket: 'myapp-2025-soknao.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYbajfZY6EdmjuEVcHRkGk_ORAclY_Pcs',
    appId: '1:78450892577:ios:c4bc2c3b387c3a1751a860',
    messagingSenderId: '78450892577',
    projectId: 'myapp-2025-soknao',
    storageBucket: 'myapp-2025-soknao.firebasestorage.app',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYbajfZY6EdmjuEVcHRkGk_ORAclY_Pcs',
    appId: '1:78450892577:ios:c4bc2c3b387c3a1751a860',
    messagingSenderId: '78450892577',
    projectId: 'myapp-2025-soknao',
    storageBucket: 'myapp-2025-soknao.firebasestorage.app',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLaD14YIQp_p8HKb0zmQx7HWL4WDN84e4',
    appId: '1:78450892577:web:a7ef4ffb64faf13e51a860',
    messagingSenderId: '78450892577',
    projectId: 'myapp-2025-soknao',
    authDomain: 'myapp-2025-soknao.firebaseapp.com',
    storageBucket: 'myapp-2025-soknao.firebasestorage.app',
  );
}
